Update pocket-ic to async version
bitfinity-network/bit-fusion-sdk pull request #125
Opened 2024-08-15 06:06 UTC by F3kilo

## Issue ticket

Issue ticket link:

## Checklist before requesting a review

### Code conventions

- [X] I have performed a self-review of my code
- [X] Every new function is documented
- [X] Object names are auto explicative
- [X] The PR follows the [project conventions](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/23330839/Conventions)
- [X] The code follows the [style guidelines of the project](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/24444929/Rust+Conventions)
- [X] The code follows the [project security best practices](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/35225620/Security+Considerations)

### Security 

- [X] The PR does not break APIs backward compatibility
- [X] The PR does not break the stable storage backward compatibility

### Testing 

- [X] Every function is properly unit tested
- [X] I have added integration tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] IC endpoints are always tested through the `canister_call!` macro

2024-08-16 07:43 UTC, ufoscout requested changes

2024-08-16 07:43 UTC, ufoscout commented on _Cargo.lock
to be removed

2024-08-19 07:02 UTC, F3kilo commented on _Cargo.lock
Done

2024-08-19 07:03 UTC, F3kilo commented on _Cargo.lock
Removed

2024-08-20 09:11 UTC, ufoscout approved these changes

2024-08-20 09:11 UTC, merged