[EPROD-963] Bridge Deployer
bitfinity-network/bit-fusion-sdk pull request #131
Opened 2024-08-26 07:16 UTC by itsyaasir

## Issue ticket

Issue ticket link:

## Checklist before requesting a review

### Code conventions

- [x] Every new function is documented
- [x] I have performed a self-review of my code
- [x] Object names are auto explicative
- [x] The PR follows the [project conventions](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/23330839/Conventions)
- [x] The code follows the [style guidelines of the project](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/24444929/Rust+Conventions)
- [x] The code follows the [project security best practices](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/35225620/Security+Considerations)

### Security 

- [x] The PR does not break APIs backward compatibility
- [x] The PR does not break the stable storage backward compatibility

### Testing 

- [x] Every function is properly unit tested
- [x] I have added integration tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] IC endpoints are always tested through the `canister_call!` macro

2024-08-28 09:00 UTC, ufoscout requested changes

2024-08-28 09:00 UTC, ufoscout commented on src/bridge-deployer/src/commands/upgrade.rs
> +pub struct UpgradeCommands {
Add description

2024-08-28 09:00 UTC, ufoscout commented on src/bridge-deployer/src/commands/reinstall.rs
> +pub struct ReinstallCommands {
Add description

2024-08-28 09:00 UTC, ufoscout commented on src/bridge-deployer/src/commands/deploy.rs
> +pub struct DeployCommands {
Add description

2024-08-29 15:47 UTC, F3kilo approved these changes

2024-08-29 15:47 UTC, F3kilo commented on src/bridge-deployer/src/config/icrc.rs
> +}
Let's add doc comments here too, since they will be a part of CLI help.

2024-08-29 15:47 UTC, F3kilo commented on src/bridge-deployer/src/config/rune.rs
> +}
Let's add doc comments here too, since they will be a part of CLI help.

2024-08-29 15:58 UTC, veeso requested changes
LGTM except for what kirill has pointed out that should be fixed

2024-08-30 12:23 UTC, ufoscout approved these changes

2024-08-30 12:34 UTC, veeso approved these changes

2024-08-30 13:09 UTC, merged