EPROD-965 brc20 bridge (deposit)
bitfinity-network/bit-fusion-sdk pull request #132
Opened 2024-08-26 15:07 UTC by veeso

## Issue ticket

Issue ticket link:

## Checklist before requesting a review

### Code conventions

- [ ] I have performed a self-review of my code
- [ ] Every new function is documented
- [ ] Object names are auto explicative
- [ ] The PR follows the [project conventions](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/23330839/Conventions)
- [ ] The code follows the [style guidelines of the project](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/24444929/Rust+Conventions)
- [ ] The code follows the [project security best practices](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/35225620/Security+Considerations)

### Security 

- [ ] The PR does not break APIs backward compatibility
- [ ] The PR does not break the stable storage backward compatibility

### Testing 

- [ ] Every function is properly unit tested
- [ ] I have added integration tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] IC endpoints are always tested through the `canister_call!` macro

2024-08-30 09:06 UTC, F3kilo approved these changes
Great job. I have only a couple of refactoring suggestions.

2024-08-30 09:06 UTC, F3kilo commented on src/brc20-bridge/src/ops.rs
> +        tx_id: H256,
Dst address can be queried from (Signed)MintOrder. So no need to store it explicitly.

2024-08-30 09:06 UTC, F3kilo commented on src/brc20-bridge/src/ops.rs
> +        dst_token: H160,
This fout parameters can be packed into a struct, and it can be re-used in both variants:
- `AwaitImputs`
- `AwaitConfirmations`

2024-08-31 11:00 UTC, ufoscout requested changes

2024-08-31 11:00 UTC, ufoscout commented on src/brc20-bridge/src/ops.rs
> +                "ConfirmMintOrder task should progress only on the Minted EVM event".into(),
Where does this happen?

2024-09-02 08:04 UTC, veeso commented on src/integration-tests/tests/utils/brc20_helper.rs
> +        self.wait_for_confirmations(&commit_txid, 6).await?;
@ufoscout 6 confirmations is required by IC bitcoin

2024-09-02 08:05 UTC, veeso commented on src/integration-tests/tests/dfx_tests/mod.rs
>  // mod erc20_bridge;
@ufoscout I don't know, they've been there for months, I think it's a leftover. I'll ask on the chat

2024-09-02 08:05 UTC, veeso commented on src/brc20-bridge/src/state.rs
> +const DEFAULT_INDEXER_CONSENSUS_THRESHOLD: u8 = 2;
I've copied from Yasir's PR

2024-09-02 08:07 UTC, veeso commented on src/brc20-bridge/src/ops.rs
> +                "ConfirmMintOrder task should progress only on the Minted EVM event".into(),
```rust
async fn on_wrapped_token_minted(
        _ctx: RuntimeState<Self>,
        event: MintedEventData,
    ) -> Option<OperationAction<Self>> {
        log::debug!(
            "on_wrapped_token_minted nonce {nonce} {event:?}",
            nonce = event.nonce
        );

        Some(OperationAction::Update {
            nonce: event.nonce,
            update_to: Self::MintOrderConfirmed { data: event },
        })
    }
```

2024-09-02 12:18 UTC, veeso commented on src/bridge-client/Cargo.toml
> +brc20-bridge = { path = "../brc20-bridge" }
It'll be worked on https://infinityswap.atlassian.net/browse/EPROD-989

2024-09-04 11:09 UTC, ufoscout commented on src/brc20-bridge/src/memory.rs
> +//! DO NOT USE ANY MEMORY ID BELOW 10, since used by the sdk
I would not use anything below 100 to leave more IDs for future upgrades of the SDK

2024-09-04 12:51 UTC, ufoscout requested changes

2024-09-04 12:51 UTC, ufoscout commented on src/brc20-bridge/src/state/config.rs
> +        let mut buf = Vec::with_capacity(
The effort is remarkable, but it is definitely more maintanable to use candid::Encode here instead

2024-09-04 12:51 UTC, ufoscout commented on src/brc20-bridge/src/ledger/utxo_details.rs
> +        let mut buff = Vec::with_capacity(
Please use candid encoder instead

2024-09-04 12:51 UTC, ufoscout commented on src/brc20-bridge/src/state/master_key.rs
> +    pub chain_code: ChainCode,
What are the guarantees that the `PublicKey` and `ChainCode` struct do not change in the future? As these are external structs, we have no control on them, if they get changed our storage will be broken

2024-09-04 14:22 UTC, ufoscout approved these changes

2024-09-04 14:55 UTC, merged