tests: Runes minter notification unit tests
bitfinity-network/bit-fusion-sdk pull request #142
Opened 2024-09-04 09:27 UTC by Maximkaaa

## Issue ticket

Issue ticket link:

## Checklist before requesting a review

### Code conventions

- [ ] I have performed a self-review of my code
- [ ] Every new function is documented
- [ ] Object names are auto explicative
- [ ] The PR follows the [project conventions](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/23330839/Conventions)
- [ ] The code follows the [style guidelines of the project](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/24444929/Rust+Conventions)
- [ ] The code follows the [project security best practices](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/35225620/Security+Considerations)

### Security 

- [ ] The PR does not break APIs backward compatibility
- [ ] The PR does not break the stable storage backward compatibility

### Testing 

- [ ] Every function is properly unit tested
- [ ] I have added integration tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] IC endpoints are always tested through the `canister_call!` macro

2024-09-04 10:25 UTC, veeso requested changes

2024-09-04 10:25 UTC, veeso commented on src/rune-bridge/src/ops/tests/await_confirmations.rs
> +                name: RuneName::from_str("A").unwrap(),
I'm not sure if it's the same, but for coherence with real-case scenario, the rune name here should be randomized in order to have each runetoWrap different

2024-09-04 11:03 UTC, ufoscout approved these changes

2024-09-05 09:29 UTC, veeso commented
@Maximkaaa there are some conflicts to be fixed due to my BRC20 pr

2024-09-06 09:31 UTC, veeso approved these changes

2024-09-06 09:31 UTC, merged