[EPROD-997] create endpoint to return all memos by user
bitfinity-network/bit-fusion-sdk pull request #151
Opened 2024-09-16 16:48 UTC by itsyaasir

## Issue ticket

Issue ticket link:

## Checklist before requesting a review

### Code conventions

- [x] I have performed a self-review of my code
- [x] Every new function is documented
- [x] Object names are auto explicative
- [x] The PR follows the [project conventions](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/23330839/Conventions)
- [x] The code follows the [style guidelines of the project](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/24444929/Rust+Conventions)
- [x] The code follows the [project security best practices](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/35225620/Security+Considerations)

### Security 

- [x] The PR does not break APIs backward compatibility
- [x] The PR does not break the stable storage backward compatibility

### Testing 

- [x] Every function is properly unit tested
- [x] I have added integration tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] IC endpoints are always tested through the `canister_call!` macro

2024-09-17 12:53 UTC, ufoscout requested changes

2024-09-17 12:53 UTC, ufoscout commented on src/bridge-canister/src/operation_store.rs
> +        self.memo_operation_map
This forces us to loop through all available memos, instead, we would like to invert the map structure from `memo_operation_map: StableMultimap<Memo, H160, OperationId, M>,` to `memo_operation_map: StableMultimap<H160, Memo, OperationId, M>,`

2024-09-19 08:16 UTC, ufoscout approved these changes

2024-09-23 06:00 UTC, F3kilo approved these changes

2024-09-23 08:44 UTC, veeso approved these changes

2024-09-23 12:11 UTC, merged