[EPROD-1013] Init btc bridge with ckBTC parameters
bitfinity-network/bit-fusion-sdk pull request #160
Opened 2024-09-26 06:39 UTC by Maximkaaa

## Issue ticket

Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-1013

## Checklist before requesting a review

### Code conventions

- [ ] I have performed a self-review of my code
- [ ] Every new function is documented
- [ ] Object names are auto explicative
- [ ] The PR follows the [project conventions](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/23330839/Conventions)
- [ ] The code follows the [style guidelines of the project](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/24444929/Rust+Conventions)
- [ ] The code follows the [project security best practices](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/35225620/Security+Considerations)

### Security 

- [ ] The PR does not break APIs backward compatibility
- [ ] The PR does not break the stable storage backward compatibility

### Testing 

- [ ] Every function is properly unit tested
- [ ] I have added integration tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] IC endpoints are always tested through the `canister_call!` macro

2024-09-26 08:18 UTC, ufoscout requested changes

2024-09-26 08:18 UTC, ufoscout commented on src/bridge-deployer/src/config/btc.rs
> +                "either all or none of the `ledger`, `minter`, `fee` arguments must be provided",
With clap you can force a set of values to be provided all together

2024-09-26 09:26 UTC, F3kilo approved these changes

2024-09-26 09:59 UTC, veeso requested changes

2024-09-26 09:59 UTC, veeso commented on src/bridge-did/src/init/btc.rs
> +                Principal::from_text("mqygn-kiaaa-aaaar-qaadq-cai").unwrap()
I would move principals and fees as const

2024-09-30 12:00 UTC, veeso approved these changes

2024-09-30 13:49 UTC, ufoscout approved these changes

2024-10-02 04:05 UTC, merged