Eprod 1003 use batched mint order processing in btc bridge
bitfinity-network/bit-fusion-sdk pull request #164
Opened 2024-09-27 13:51 UTC by veeso

## Issue ticket

Issue ticket link:

## Checklist before requesting a review

### Code conventions

- [ ] I have performed a self-review of my code
- [ ] Every new function is documented
- [ ] Object names are auto explicative
- [ ] The PR follows the [project conventions](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/23330839/Conventions)
- [ ] The code follows the [style guidelines of the project](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/24444929/Rust+Conventions)
- [ ] The code follows the [project security best practices](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/35225620/Security+Considerations)

### Security 

- [ ] The PR does not break APIs backward compatibility
- [ ] The PR does not break the stable storage backward compatibility

### Testing 

- [ ] Every function is properly unit tested
- [ ] I have added integration tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] IC endpoints are always tested through the `canister_call!` macro

2024-09-30 14:02 UTC, ufoscout approved these changes

2024-10-01 07:19 UTC, F3kilo requested changes

2024-10-01 07:19 UTC, F3kilo commented on src/btc-bridge/src/canister.rs
> -
Can we return SignedOrders instead of removing endpoints?

2024-10-01 07:19 UTC, F3kilo commented on src/bridge-did/src/operations/btc.rs
> +        order: MintOrder,
As far as I understand, the `eth_address` is equal to `order.recipient`. So, we can remove it.

2024-10-01 07:19 UTC, F3kilo commented on src/bridge-did/src/operations/btc.rs
> +        order: SignedOrders,
The eth address can be red from order like: `order.reader().get_recipient()`.

2024-10-02 04:39 UTC, Maximkaaa approved these changes

2024-10-02 12:18 UTC, F3kilo approved these changes

2024-10-02 12:22 UTC, merged