Services instead service tasks
bitfinity-network/bit-fusion-sdk pull request #178
Opened 2024-10-16 09:29 UTC by F3kilo

## Issue ticket

Issue ticket link:

## Checklist before requesting a review

### Code conventions

- [ ] I have performed a self-review of my code
- [ ] Every new function is documented
- [ ] Object names are auto explicative
- [ ] The PR follows the [project conventions](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/23330839/Conventions)
- [ ] The code follows the [style guidelines of the project](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/24444929/Rust+Conventions)
- [ ] The code follows the [project security best practices](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/35225620/Security+Considerations)

### Security 

- [ ] The PR does not break APIs backward compatibility
- [ ] The PR does not break the stable storage backward compatibility

### Testing 

- [ ] Every function is properly unit tested
- [ ] I have added integration tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] IC endpoints are always tested through the `canister_call!` macro

2024-10-22 09:19 UTC, ufoscout requested changes

2024-10-22 09:19 UTC, ufoscout commented on src/bridge-did/src/events.rs
> +    pub fn try_decode_reschedule_operation_id(&self) -> Option<OperationId> {
Why not returning the error?

2024-10-22 13:52 UTC, veeso requested changes

2024-10-22 13:52 UTC, veeso commented on src/rune-bridge/src/ops/events_handler.rs
> +        match event.notification_type {
use a function to handle inner nesting

2024-10-23 10:24 UTC, ufoscout approved these changes

2024-10-23 12:00 UTC, veeso approved these changes

2024-10-24 06:28 UTC, merged