[EPROD-1033] Deploy BFT contracts using forge
bitfinity-network/bit-fusion-sdk pull request #179
Opened 2024-10-16 13:20 UTC by itsyaasir

## Issue ticket

Issue ticket link:

## Checklist before requesting a review

### Code conventions

- [x] I have performed a self-review of my code
- [x] Every new function is documented
- [x] Object names are auto explicative
- [x] The PR follows the [project conventions](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/23330839/Conventions)
- [x] The code follows the [style guidelines of the project](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/24444929/Rust+Conventions)
- [x] The code follows the [project security best practices](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/35225620/Security+Considerations)

### Security 

- [x] The PR does not break APIs backward compatibility
- [x] The PR does not break the stable storage backward compatibility

### Testing 

- [x] Every function is properly unit tested
- [x] I have added integration tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] IC endpoints are always tested through the `canister_call!` macro

2024-10-21 07:22 UTC, ufoscout requested changes

2024-10-21 07:22 UTC, ufoscout commented on just/dfx.just
> +  dfx start --background --clean 2> "{{DFX_LOGFILE}}"
Why was `--enable-bitcoin` removed? We need this for testing runes and brc20

2024-10-21 07:22 UTC, ufoscout commented on solidity/src/WrappedTokenDeployer.sol
>  pragma solidity >=0.5.0;
0.5.0?!

2024-10-22 08:02 UTC, ufoscout requested changes

2024-10-22 08:02 UTC, ufoscout commented on solidity/deploy.sh
We removed all scripts. Do we need this file?

2024-10-22 10:00 UTC, Maximkaaa approved these changes

2024-10-22 11:11 UTC, veeso approved these changes

2024-10-22 12:29 UTC, ufoscout approved these changes

2024-10-22 12:41 UTC, merged