EPROD 1038 add deployer tests
bitfinity-network/bit-fusion-sdk pull request #181
Opened 2024-10-17 12:47 UTC by veeso

- **EPROD-1038 add deployer tests**
- **fix: deploy tests ok**

2024-10-22 12:48 UTC, ufoscout reviewed
@veeso This PR modifies the hardhat ts scripts, but they are removed in EPROD-1047

2024-10-23 08:56 UTC, ufoscout requested changes
Please fix the merge conflicts

2024-10-24 07:05 UTC, ufoscout requested changes

2024-10-24 08:18 UTC, blutooth commented on src/bridge-deployer/src/commands/mod.rs
>          info!("Deploying BFT bridge");
Symbol should be BTF

2024-10-24 10:31 UTC, ufoscout approved these changes

2024-10-24 10:31 UTC, merged