Deployer fixes / deploy, withdraw commands in bridge-tool
bitfinity-network/bit-fusion-sdk pull request #186
Opened 2024-11-04 08:50 UTC by Maximkaaa

## Issue ticket

Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-1034

## Checklist before requesting a review

### Code conventions

- [ ] I have performed a self-review of my code
- [ ] Every new function is documented
- [ ] Object names are auto explicative
- [ ] The PR follows the [project conventions](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/23330839/Conventions)
- [ ] The code follows the [style guidelines of the project](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/24444929/Rust+Conventions)
- [ ] The code follows the [project security best practices](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/35225620/Security+Considerations)

### Security 

- [ ] The PR does not break APIs backward compatibility
- [ ] The PR does not break the stable storage backward compatibility

### Testing 

- [ ] Every function is properly unit tested
- [ ] I have added integration tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] IC endpoints are always tested through the `canister_call!` macro

2024-11-04 10:03 UTC, veeso requested changes

2024-11-04 10:03 UTC, veeso commented on src/bridge-deployer/Cargo.toml
> +reqwest = "0.12"
use workspace toml

2024-11-04 10:03 UTC, veeso commented on src/bridge-tool/Cargo.toml
> +reqwest = "0.12"
workspace dep

2024-11-05 06:59 UTC, ufoscout approved these changes

2024-11-05 08:17 UTC, F3kilo approved these changes

2024-11-05 09:10 UTC, veeso approved these changes

2024-11-05 09:19 UTC, merged