Rename BFT to BTF across the bridge modules for consistency
bitfinity-network/bit-fusion-sdk pull request #189
Opened 2024-11-05 09:05 UTC by itsyaasir

## Issue ticket

Issue ticket link:

## Checklist before requesting a review

### Code conventions

- [x] I have performed a self-review of my code
- [x] Every new function is documented
- [x] Object names are auto explicative
- [x] The PR follows the [project conventions](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/23330839/Conventions)
- [x] The code follows the [style guidelines of the project](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/24444929/Rust+Conventions)
- [x] The code follows the [project security best practices](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/35225620/Security+Considerations)

### Security 

- [x] The PR does not break APIs backward compatibility
- [x] The PR does not break the stable storage backward compatibility

### Testing 

- [x] Every function is properly unit tested
- [x] I have added integration tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] IC endpoints are always tested through the `canister_call!` macro

2024-11-05 10:21 UTC, veeso requested changes

2024-11-05 10:21 UTC, veeso commented on solidity/src/test_contracts/NewBftBridge.sol
>  import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
should this file be renamed too?

2024-11-05 10:21 UTC, veeso commented on solidity/test/contract_tests/BftBridge.t.sol
>  import "forge-std/Test.sol";
should this file be renamed too?

2024-11-06 09:19 UTC, Maximkaaa requested changes
I think these should be renamed also:
![image](https://github.com/user-attachments/assets/e7d72aa0-22a5-49de-a6f0-f8eaa434e27e)

2024-11-06 09:19 UTC, Maximkaaa commented on solidity/script/UpgradeBFT.s.sol
Rename the file

2024-11-06 09:20 UTC, Maximkaaa commented
Yeah, those files from my screenshot got in there after you did search and replace. Sorry :-)

2024-11-06 09:49 UTC, F3kilo approved these changes

2024-11-06 10:17 UTC, ufoscout approved these changes

2024-11-07 03:52 UTC, Maximkaaa approved these changes

2024-11-07 08:08 UTC, veeso approved these changes

2024-11-08 07:50 UTC, merged