EPROD 855 create deployment scripts for devnet testnet mainnet
bitfinity-network/bit-fusion-sdk pull request #47
Opened 2024-05-15 12:59 UTC by veeso

- **fix: wip**
- **wip**
- **wip**
- **wip**

## Issue ticket

Issue ticket link:

## Checklist before requesting a review

### Code conventions

- [ ] I have performed a self-review of my code
- [ ] Every new function is documented
- [ ] Object names are auto explicative
- [ ] The PR follows the [project conventions](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/23330839/Conventions)
- [ ] The code follows the [style guidelines of the project](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/24444929/Rust+Conventions)
- [ ] The code follows the [project security best practices](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/35225620/Security+Considerations)

### Security 

- [ ] The PR does not break APIs backward compatibility
- [ ] The PR does not break the stable storage backward compatibility

### Testing 

- [ ] Every function is properly unit tested
- [ ] I have added integration tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] IC endpoints are always tested through the `canister_call!` macro

2024-05-17 06:49 UTC, itsyaasir reviewed
The script looks good to me but with these much scripts it can get confusing real fast. Can we have an md file on what each script does and which services are deployed as well ?

Also I can see each script is aimed at deploying a single bridge services so for `erc20-bridge` will deploy erc20 services ? Does this mean if someone wants to deploy another bridging; they will have to stop the first in order to deploy the second ? What if someone wants to deploy all of the briding services, will there be conflict of services deployed in the script ?

2024-05-17 07:30 UTC, Maximkaaa requested changes

2024-05-17 07:30 UTC, Maximkaaa commented on scripts/deploy/btc-bridge.sh
> +SIGNING_STRATEGY="variant { ManagementCanister = record { key_id = variant { Dfx }; } }"
Here and for other canisters, for local dfx deployment we should use key_id `Dfx`, and for IC deployment  - `Production`. I don't think we need to use the local signing strategy (with PK) at all.

2024-05-17 07:30 UTC, Maximkaaa commented on scripts/deploy/btc-bridge.sh
> +LOG_SETTINGS="opt record { enable_console=false; in_memory_records=opt 10000; log_filter=opt \"info,evm_core=debug,evm=debug\"; }"
Probably we don't need `debug` log level for evm and canisters in the mainnet, only with local deployment? Otherwaise the logs are to clogged to find anything.

2024-05-17 07:30 UTC, Maximkaaa commented on scripts/deploy/btc-bridge.sh
> +  assert_isset_param "$CKBTC_LEDGER" "CKBTC_LEDGER"
We can set these values right in the script as these are constants. It would simplify usage of the script a lot.

2024-05-17 07:30 UTC, Maximkaaa commented on scripts/deploy/deploy_functions.sh
> +  dfx identity new --storage-mode=plaintext alice
You can use `--force` flag to prevent dfx error message in case the identity already exist.

2024-05-20 07:57 UTC, veeso commented on docs/deploy.md
> +- Use `dfx` version <= `0.17.x` (for now). [Get `dfx` here](https://internetcomputer.org/docs/current/developer-docs/getting-started/install/#installing-dfx) if you don't have it already.
It was an issue with 0.18 but it has been fixed actually. Removed

2024-05-20 07:59 UTC, itsyaasir approved these changes

2024-05-22 08:21 UTC, F3kilo approved these changes

2024-05-22 13:08 UTC, merged