Operations log in runes and erc20 bridges
bitfinity-network/bit-fusion-sdk pull request #83
Opened 2024-06-19 07:08 UTC by Maximkaaa

## Issue ticket

Issue ticket link:
* https://infinityswap.atlassian.net/browse/EPROD-836
* https://infinityswap.atlassian.net/browse/EPROD-894

## Checklist before requesting a review

### Code conventions

- [ ] I have performed a self-review of my code
- [ ] Every new function is documented
- [ ] Object names are auto explicative
- [ ] The PR follows the [project conventions](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/23330839/Conventions)
- [ ] The code follows the [style guidelines of the project](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/24444929/Rust+Conventions)
- [ ] The code follows the [project security best practices](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/35225620/Security+Considerations)

### Security 

- [ ] The PR does not break APIs backward compatibility
- [ ] The PR does not break the stable storage backward compatibility

### Testing 

- [ ] Every function is properly unit tested
- [ ] I have added integration tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] IC endpoints are always tested through the `canister_call!` macro

2024-06-21 08:05 UTC, veeso requested changes

2024-06-21 08:05 UTC, veeso commented on src/rune-bridge/src/state.rs
> +        for rune_info in self.runes.values() {
you can use self.runes.values().find(...)

2024-06-21 14:16 UTC, ufoscout requested changes
@Maximkaaa please fix the branch conflicts so we can proceed with the review

2024-06-21 14:16 UTC, ufoscout commented on .cargo/audit.toml
> +ignore = ["RUSTSEC-2023-0071", "RUSTSEC-2024-0332", "RUSTSEC-2024-0336", "RUSTSEC-2024-0344"]
"RUSTSEC-2024-0344" to be removed as already fix in `main`

2024-06-24 13:18 UTC, ufoscout commented on src/integration-tests/tests/dfx_tests/runes.rs
> +                .update::<_, _>("get_operations_list", (eth_address,))
Instead of this, please add the method to the client and use it

2024-06-24 13:18 UTC, ufoscout commented on src/integration-tests/tests/pocket_ic_integration_test/erc20_minter.rs
> +            "get_mint_order",
same as before, better to always implement these calls on the client

2024-06-24 13:19 UTC, ufoscout commented on src/integration-tests/tests/pocket_ic_integration_test/erc20_minter.rs
> +    let operations = erc20_minter_client
same as before, better to always implement these calls on the client

2024-06-25 08:52 UTC, ufoscout approved these changes

2024-06-25 08:59 UTC, veeso approved these changes

2024-06-25 09:29 UTC, merged