EPROD 889 f11 logs are retrieved from an unbounded number of blocks
bitfinity-network/bit-fusion-sdk pull request #86
Opened 2024-06-19 14:49 UTC by veeso

- **EPROD-889 set a boundary for get logs calls**
- **fix: lint**

## Issue ticket

Issue ticket link:

## Checklist before requesting a review

### Code conventions

- [ ] I have performed a self-review of my code
- [ ] Every new function is documented
- [ ] Object names are auto explicative
- [ ] The PR follows the [project conventions](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/23330839/Conventions)
- [ ] The code follows the [style guidelines of the project](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/24444929/Rust+Conventions)
- [ ] The code follows the [project security best practices](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/35225620/Security+Considerations)

### Security 

- [ ] The PR does not break APIs backward compatibility
- [ ] The PR does not break the stable storage backward compatibility

### Testing 

- [ ] Every function is properly unit tested
- [ ] I have added integration tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] IC endpoints are always tested through the `canister_call!` macro

2024-06-21 14:15 UTC, ufoscout requested changes

2024-06-21 14:15 UTC, ufoscout commented on src/minter-contract-utils/src/evm_bridge.rs
> +    pub last_log_block: Option<u64>,
The `EvmParams` are values queried from the evm canister. The `last_log_block` is not one of them, it should not be placed here.

2024-06-21 14:15 UTC, ufoscout commented on src/minter-contract-utils/src/evm_bridge.rs
> +    pub fn set_last_log_block_error(&mut self) {
This logic is confusing and does not fix what reported by F11. The issue has to be fixed by paginating if more than X blocks are to be queried

2024-06-21 14:15 UTC, ufoscout commented on src/icrc2-minter/src/tasks.rs
> +        let logs = match BridgeEvent::collect_logs(
here it is required to paginate to queries if more than X blocks have to be fetched.
E.g., pseudo code:
```
let to_block = from_block + X;

///  loop until there are more than X blocks in the response
while query_logs.query().blocks >= X {
    ...
}
```

2024-06-25 07:45 UTC, ufoscout requested changes

2024-06-25 07:45 UTC, ufoscout commented on src/minter-contract-utils/src/bft_bridge_api.rs
> +            match Self::collect_logs_from_to(
Is the block range inclusive? If yes, then the end block is fecthed twice as start block of the next loop

2024-06-25 07:45 UTC, ufoscout commented on src/minter-contract-utils/src/bft_bridge_api.rs
> +        blocks_to_fetch: u64,
this should be renamed `to_blocks` and should be Optional (if 'None`, use `Block::Latest`)

2024-06-25 07:45 UTC, ufoscout commented on src/minter-contract-utils/src/bft_bridge_api.rs
> +                    from_block += offset;
This sum, and the one at line 266, can be bigger than `to_blocks`

2024-06-26 09:35 UTC, F3kilo approved these changes
Can we write tests for the pagination?

2024-06-26 13:14 UTC, ufoscout requested changes

2024-06-26 13:14 UTC, ufoscout commented on src/rune-bridge/src/scheduler.rs
> +        let last_block = client.get_block_number().await.into_scheduler_result()?;
avoid this calls and use `None` instead of `Some(last_block)`

2024-06-26 13:14 UTC, ufoscout commented on src/icrc2-minter/src/tasks.rs
> +        let last_block = client.get_block_number().await.into_scheduler_result()?;
avoid this calls and use `None` instead of `Some(last_block)`

2024-06-26 13:14 UTC, ufoscout commented on src/erc20-minter/src/tasks.rs
> +        let last_block = client.get_block_number().await.into_scheduler_result()?;
avoid this calls and use `None` instead of `Some(last_block)`

2024-06-26 13:14 UTC, ufoscout commented on src/btc-bridge/src/scheduler.rs
> +        let last_block = client.get_block_number().await.into_scheduler_result()?;
avoid this calls and use `None` instead of `Some(last_block)`

2024-06-26 13:14 UTC, ufoscout commented on src/minter-contract-utils/src/bft_bridge_api.rs
>      pub async fn collect_logs(
Please add tests for various combinations of `to_block`

2024-06-26 13:14 UTC, ufoscout commented on src/minter-contract-utils/src/bft_bridge_api.rs
> +                        from_block + offset,
replace with `to_block_for_page`

2024-06-26 13:14 UTC, ufoscout commented on src/minter-contract-utils/src/bft_bridge_api.rs
> +                    from_block += offset + 1;
replace with: `from_block = to_block_for_page + 1`

2024-06-26 15:45 UTC, ufoscout approved these changes

2024-06-26 16:29 UTC, merged