EPROD-851 check for changes before rebuilding solidity contracts
bitfinity-network/bit-fusion-sdk pull request #89
Opened 2024-06-27 12:31 UTC by veeso

## Issue ticket

Issue ticket link:

## Checklist before requesting a review

### Code conventions

- [ ] I have performed a self-review of my code
- [ ] Every new function is documented
- [ ] Object names are auto explicative
- [ ] The PR follows the [project conventions](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/23330839/Conventions)
- [ ] The code follows the [style guidelines of the project](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/24444929/Rust+Conventions)
- [ ] The code follows the [project security best practices](https://infinityswap.atlassian.net/wiki/spaces/CPROD/pages/35225620/Security+Considerations)

### Security 

- [ ] The PR does not break APIs backward compatibility
- [ ] The PR does not break the stable storage backward compatibility

### Testing 

- [ ] Every function is properly unit tested
- [ ] I have added integration tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] IC endpoints are always tested through the `canister_call!` macro

2024-06-27 12:34 UTC, veeso commented on src/integration-tests/tests/utils/error.rs
> +        Self::CanisterClient(CanisterClientError::PocketIcTestError(e))
This caused infinite recursion

2024-06-28 07:45 UTC, ufoscout requested changes

2024-06-28 07:45 UTC, ufoscout commented on src/minter-contract-utils/build.rs
> +impl SolidityFileTimesWatcher {
The logic could be better isolated this way:
- SolidityFileTimesWatcher to SolidityBuilder
- make save_file_times fn private
- add a new fn "build_updated_contracts" 
- in the `main` fn, simply call build_updated_contracts
- `save_file_times()` should not be called externally

And add tests! an error here could lead to the deployment of a wrong contract

2024-06-28 07:45 UTC, ufoscout commented on src/minter-contract-utils/build.rs
> +        let times_file_path = root_path.join("target/.solidity_file_timestamps.toml");
instead of adding a new dependency (i.e. toml) use serde_json

2024-06-28 07:45 UTC, ufoscout commented on src/minter-contract-utils/build.rs
> +    "lib/forge-std/src/",
do we really need to monitor the lib folder? I guess `src` is enough

2024-06-28 07:45 UTC, ufoscout commented on src/minter-contract-utils/build.rs
> +        for file_in_dir in std::fs::read_dir(path)? {
is this recursive? `walkdir` is a common option to simplify this type of operations

2024-06-28 07:45 UTC, ufoscout commented on src/minter-contract-utils/build.rs
> +struct SolidityFileTimesWatcher {
This could live in the solidity helper

2024-07-01 07:07 UTC, ufoscout approved these changes

2024-07-01 08:08 UTC, F3kilo approved these changes

2024-07-01 08:47 UTC, merged